doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  proxy_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Proxies' # optionnel mais souvent utile
  hydrator_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators'
  default_database: "%env(resolve:MONGODB_DB)%"
  
  connections:
    default:
      server: "%env(resolve:MONGODB_URL)%"

  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          dir: "%kernel.project_dir%/src/Document"
          mapping: true
          type: attribute
          prefix: 'App\Document'
          is_bundle: false
          alias: App
    
