# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # protection CSRF activée globalement
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
        # Gestion des sessions
    session:
        handler_id: null
        cookie_lifetime: 3600   # 1 heure
        cookie_secure: auto     # Sécurisation du cookie selon l'environnement
        cookie_httponly: true   # Empêche l'accès aux cookies depuis JavaScript


    #esi: true
    #fragments: true
    http_method_override: true


