
services:
  www:
    build: docker/php
    container_name: codebyaurore_php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/php/vhosts:/etc/apache2/site-enabled
    networks:
      - codebyaurore
###> doctrine/doctrine-bundle ###
  db:
    image: mysql
    container_name: codebyaurore_mysql
    volumes:
      - ./var/db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - codebyaurore

  phpmyadmin:
    image: phpmyadmin
    container_name: codebyaurore_phpmyadmin
    ports:
      - 8780:80
    networks:
      - codebyaurore

volumes:
  db_data:

networks:
  codebyaurore: