services:
  www:
    user: "${UID}:${GID}"
    environment:
      - APP_ENV=dev
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./docker/php/vhosts:/etc/apache2/sites-enabled

  mysql:
    ports:
      - "3307:3306"
    networks:
      - codebyaurore
    volumes:
      - ./var/db_data:/var/lib/mysql

  mongodb:
    ports:
      - "27017:27017"
    networks:
      - codebyaurore

  phpmyadmin:
    image: phpmyadmin
    container_name: codebyaurore_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - codebyaurore
    profiles:
      - dev

networks:
  codebyaurore:

volumes:
  mongo_data: