
services:
  www:
    build: docker/php
    container_name: codebyaurore_php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/php/vhosts:/etc/apache2/site-enabled
###> doctrine/doctrine-bundle ###
  mysql:
    image: mysql
    container_name: codebyaurore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: codebyaurore
    ports:
      - "3307:3306" 
    volumes:
      - ./var/db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: codebyaurore_phpmyadmin
    depends_on:
      - mysql
    ports:
    
      - 8081:80
    environment:
      PMA_HOST: mysql

volumes:
  mysql_data: