
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebyaurore_php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    env_file:
      - .env.local
    depends_on:
      - mongodb
    networks:
      - codebyaurore
###> doctrine/doctrine-bundle ###
  mysql:
    image: mysql
    container_name: codebyaurore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: codebyaurore
    ports:
      - "3307:3306"
    volumes:
      - ./var/db_data:/var/lib/mysql
    networks:
      - codebyaurore

  phpmyadmin:
    image: phpmyadmin
    container_name: codebyaurore_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
    networks:
      - codebyaurore

  mongodb:
    image: mongo:6
    container_name: codebyaurore_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - codebyaurore
  

networks:
  codebyaurore:
volumes:
  mongo_data:
