services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebyaurore_php
    restart: always
    env_file:
      - .env.prod
    ports:
      - 8080:8080
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./.env.prod:/var/www/html/.env
    depends_on:
      - mysql
    networks:
      - codebyaurore

  mysql:
    image: mysql
    container_name: codebyaurore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./var/db_data:/var/lib/mysql
    networks:
      - codebyaurore

  mongodb:
    image: mongo:6.0
    restart: always
    container_name: codebyaurore_mongodb
    command: ["mongod", "--tlsMode", "disabled"]
    volumes:
      - mongo_data:/data/db
    networks:
      - codebyaurore

networks:
  codebyaurore:

volumes:
  mongo_data: