controllers:
    resource: ../src/Controller/
    type: attribute

nelmio_csp_report:
    path: /nelmio/csp/report
    controller: Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController::reportAction
