# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $twig: '@twig'
    App\Controller\SecurityController:
        arguments:
            $loginRateLimiter: '@login.limiter'
    login.limiter:
        alias: 'limiter.login'
    limiter.storage.cache_app:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            - '@cache.app'

    Symfony\Component\RateLimiter\Storage\StorageInterface: '@limiter.storage.cache_app'
